---
title: "Glossary"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: default
    css: "theme3.css"
toc_depth: 1
number_sections: true
editor_options:
  chunk_output_type: console
---

<style type="text/css">
  body{
  line-height: 2
  }

</style>

### A  

[Ametabolism -](https://en.wikipedia.org/wiki/Ametabolism) A type of growth or life cycle in insects in which there is a slight or no metamorphosis, and only a gradual increase in size. This is only present in primitive wingless insects in the orders Archaeognatha and Zygentoma.

[Amino Acid -]() Chemical building blocks that are joined by peptide linkages to form a polypeptide chain of protein.

[Annotation, Gene](https://support.nlm.nih.gov/knowledgebase/article/KA-03574/en-us) The process of finding and designating the locations of individual genes and other featres on raw DNA sequences.

[Assay -](https://www.sciencedirect.com/topics/pharmacology-toxicology-and-pharmaceutical-science/bioassay) A laboratory test to find the measure of the amount of a specific substance.

### B  

[BLAST -](https://blast.ncbi.nlm.nih.gov/Blast.cgi) Software that finds regions of similarity between biological sequences by comparing nucleotide or protein sequences to sequence databases and computing their statistical significance. There are specialized versions of BLAST that can be used to find conserved domains, search immunoglobin and T cell receptor sequences, vector contamination, and many other applications. While this program is more accurate than DIAMOND it is heavier computationally.

### C  

[Catabolism, Protein -](https://en.wikipedia.org/wiki/Protein_catabolism) The breakdown of proteins into smaller peptides and ultimately into amino acids.

[Chemosensation -](https://taylorandfrancis.com/knowledge/medicine-and-healthcare/anatomy/chemosensation/) The process of using chemical substances to stimulate a response in the body, particularly through the activation of chemoreceptors.

[Chemoreceptor -](https://www.osmosis.org/learn/Chemoreceptors) Special nerve cells or receptors that sense changes in the chemical composition of blood.


[Chitin -](https://en.wikipedia.org/wiki/Chitin)A fibrous substance consisting of polysaccharides and forming the major constituent in the exoskeleton of arthropods and the cell walls of fungi.

[Contig -](https://bioinformaticsworkbook.org/introduction/dataTerminology.html#gsc.tab=0) The sequence generated by aligning overlapping reads to each other.

### D  

[*De novo* gene birth -](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6542195/) The process by which new genes evolve from non-coding DNA sequences.

[DIAMOND -](https://github.com/bbuchfink/diamond) A software that aligns sequences and translated DNA searches that is designed for high-performance. This is comparable to BLAST but is typically less accurate by about 2% but is computationally lighter and faster.

[DNA Methylation - ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3174260/#:~:text=DNA%20methylation%20is%20a%20heritable,T%2C%20or%20C%20contexts.) A heritable epigenetic change where a methyl group is added to DNA that can change how the DNA is expressed.

[Domain, Protein -](https://www.ebi.ac.uk/training/online/courses/protein-classification-intro-ebi-resources/protein-classification/what-are-protein-domains/#:~:text=Domains%20are%20distinct%20functional%20and,in%20proteins%20with%20different%20functions.) Distinct structural and/or functional units in a protein, typically responsible for a particular interaction or function of the protein.

[Duplication, Gene - ](https://www.genome.gov/genetics-glossary/Duplication) A mutation where one or more copies of a DNA segment are duplicated in reproduction.


### E  

[Ecdysteroids -](https://en.wikipedia.org/wiki/Ecdysteroid) Arthropod hormones that are mainly responsible for molting, development, and to a lesser extent, reproduction.

[Epigenetic -](https://medlineplus.gov/genetics/understanding/howgeneswork/epigenome/#:~:text=%22Epi%2D%22means%20on%20or,sequence%20of%20DNA%20building%20blocks.) Factors that change gene expression but **not** the actual sequence of the DNA.


### F  


### G 

[Gene Localization -]() The contig a particular gene is located on.

[Gene Ontology -](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6438694/#:~:text=The%20Gene%20Ontology%20defines%20the,function%20of%20a%20particular%20gene.) The "universe" of possible functions a gene may have, but doesn't make any claims about the function of a particular gene.

[Gene Ontology (GO) Term -]() A term ascribed to genes through gene enrichment that describes a function a gene possesses. 

### H

[Hemimetabolism (Hemimetaboly) -](https://en.wikipedia.org/wiki/Hemimetabolism) A form of insect that has 3 distinct life stages: egg, nymph, and imago or adult. This is also referred to as partial metamorphasis or paurometabolism.

[Holometabolous -](https://en.wikipedia.org/wiki/Holometabolism) A form of insect that has 4 distinct life stages: egg, larva, pupa, and imago or adult.

[Homologous Genes -](https://bio.libretexts.org/Bookshelves/Microbiology/Microbiology_(Boundless)/07%3A_Microbial_Genetics/7.13%3A_Bioinformatics/7.13C%3A_Homologs_Orthologs_and_Paralogs) A type of gene that is inherited by 2 species that have a common ancestor. We can further subdivide homologous genes into orthologous and paralogous genes.

[Heat Stress Response (HSP) Proteins-](https://en.wikipedia.org/wiki/Hsp20) Heat Response Proteins are family of proteins that act as protein chaperones that protect other proteins against heat-induced denaturation and aggregation. Specifically, HSP20 is a group of HSP proteins with a weight of 20 kDa.


### I  
[Isoform(s) -](https://elifesciences.org/articles/34477) Proteins that are similar and perform similar roles within the cell.

### J  


### K  


### L  


### M  
[Mate Pair Sequencing -](https://www.illumina.com/science/technology/next-generation-sequencing/mate-pair-sequencing.html#:~:text=Mate%20pair%20sequencing%20involves%20generating,Structural%20variant%20detection) The generation of long-insert paired-end DNA libraries useful for applications like *de novo* sequencing, genome finishing, structural variant detection, and the identification of complex genomic rearrangements.

[Metabolism, Steroid -](https://en.wikipedia.org/wiki/Protein_metabolism) The biochemical process responsible for the synthesis of proteins and amino acids, as well as the breakdown of porteins by catabolism. 

[Monophyletic (Group, Taxon)-](https://www.mun.ca/biology/scarr/Taxon_types.htm) A taxon that includes a group of organisms most recent common ancestor and all of it's descendents.

[Multiple Sequence Alignment (MSA) Programs -](https://www.sciencedirect.com/topics/medicine-and-dentistry/multiple-sequence-alignment#) Software that attempts to align multiple DNA sequences to attain optimal matches.

### N  
[Nucleotide -](https://www.cancer.gov/publications/dictionaries/genetics-dictionary/def/nucleotide) A molecule that makes up DNA and RNA.

### O  
[Orthologous Genes -](https://bio.libretexts.org/Bookshelves/Microbiology/Microbiology_(Boundless)/07%3A_Microbial_Genetics/7.13%3A_Bioinformatics/7.13C%3A_Homologs_Orthologs_and_Paralogs) Homologous genes that diverge after a speciation event, but the gene and its main function are preserved.



### P  
[Paralogous Genes -](https://bio.libretexts.org/Bookshelves/Microbiology/Microbiology_(Boundless)/07%3A_Microbial_Genetics/7.13%3A_Bioinformatics/7.13C%3A_Homologs_Orthologs_and_Paralogs) Genes present in a particular organism that are related to each other through a gene duplication event.

[Paraphyletic (Group, Taxon) -](https://www.mun.ca/biology/scarr/Taxon_types.htm) A taxon that includes the most recent common ancestor between descendents.

[Polyphyletic (Group, Taxon) -](https://www.mun.ca/biology/scarr/Taxon_types.htm)A taxon of organisms that does not include their most recent ancestor.


### Q  


### R  

[Riparian Plots -](https://www.researchgate.net/figure/Riparian-synteny-plots-generated-using-BUSCO-gene-regions-as-anchors-showing-209_fig2_375462545) Plots used to show syntenic relationships between 2 or more species.

[RNA - ](https://www.genome.gov/genetics-glossary/RNA-Ribonucleic-Acid) Ribonucleic acid (RNA) is a copy of DNA that is used to produce proteins and assists in the translation of DNA.

### S  
[Scaffold -](https://bioinformaticsworkbook.org/introduction/dataTerminology.html#gsc.tab=0) A set of contigs that have been orientated and ordered with either mate-apired or long reads.

[Synathrope - ](https://davidrousefaicp.com/synanthropic-species-why-are-they-important-to-our-future/) Animals that live in close association with humans but are not domesticated.

[Synteny -](https://www.nature.com/scitable/topicpage/synteny-inferring-ancestral-genomes-44022/) The conservation of order of blocks within the order of 2 sets of chromosomes that are being compared to one another.

### T  

[Taxon -](https://en.wikipedia.org/wiki/Taxon) A group of one or more populations of an organism seen by taxonomists to form a unit.

[Taxonomic Rank -](https://en.wikipedia.org/wiki/Taxonomic_rank) The relative level of organisms in an ancestral or hereditary hierarchy.

[Taxonomist -]() One who studies taxonomy.

[Taxonomy -](https://en.wikipedia.org/wiki/Taxonomy_(biology)) The scientific study of naming, defining, and classifying groups of organisms based on shared characteristics.

### U  


### V  


### W  


### X  

[Xenobiotic -](https://en.wikipedia.org/wiki/Xenobiotic) A chemical substance found within an organism that is not naturally occuring within that organism.

### Y  


### Z  

[Zinc finger -](https://en.wikipedia.org/wiki/Zinc_finger) A small protein structural motif that is characterized by the coordinationg of one or more zinc ions.

[Zinc-finger proteins -](https://www.nature.com/articles/cddiscovery201771) Proteins containg a zinc finger structure.






