---
title: "Glossary"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: default
    css: "theme3.css"
toc_depth: 1
number_sections: true
editor_options:
  chunk_output_type: console
---

<style type="text/css">
  body{
  line-height: 2
  }
</style>

### A  

[Amino Acid -]() Chemical building blocks that are joined by peptide linkages to form a polypeptide chain of protein.

[Annotation, Gene](https://support.nlm.nih.gov/knowledgebase/article/KA-03574/en-us) The process of finding and designating the locations of individual genes and other featres on raw DNA sequences.

[Assay -](https://www.sciencedirect.com/topics/pharmacology-toxicology-and-pharmaceutical-science/bioassay) A laboratory test to find the measure of the amount of a specific substance.

### B  

[BLAST -](https://blast.ncbi.nlm.nih.gov/Blast.cgi) Software that finds regions of similarity between biological sequences by comparing nucleotide or protein sequences to sequence databases and computing their statistical significance. There are specialized versions of BLAST that can be used to find conserved domains, search immunoglobin and T cell receptor sequences, vector contamination, and many other applications. While this program is more accurate than DIAMOND it is heavier computationally.

### C  
[Contig -](https://bioinformaticsworkbook.org/introduction/dataTerminology.html#gsc.tab=0) The sequence generated by aligning overlapping reads to each other.

### D  

[*De novo* gene birth -](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6542195/) The process by which new genes evolve from non-coding DNA sequences.

[DIAMOND -](https://github.com/bbuchfink/diamond) A software that aligns sequences and translated DNA searches that is designed for high-performance. This is comparable to BLAST but is typically less accurate by about 2% but is computationally lighter and faster.

[DNA Methylation - ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3174260/#:~:text=DNA%20methylation%20is%20a%20heritable,T%2C%20or%20C%20contexts.) A heritable epigenetic change where a methyl group is added to DNA that can change how the DNA is expressed.

[Duplication, Gene - ](https://www.genome.gov/genetics-glossary/Duplication) A mutation where one or more copies of a DNA segment are duplicated in reproduction.


### E  
[Epigenetic -](https://medlineplus.gov/genetics/understanding/howgeneswork/epigenome/#:~:text=%22Epi%2D%22means%20on%20or,sequence%20of%20DNA%20building%20blocks.) Factors that change gene expression but **not** the actual sequence of the DNA.


### F  


### G  


### H  
[Homologous Genes -](https://bio.libretexts.org/Bookshelves/Microbiology/Microbiology_(Boundless)/07%3A_Microbial_Genetics/7.13%3A_Bioinformatics/7.13C%3A_Homologs_Orthologs_and_Paralogs) A type of gene that is inherited by 2 species that have a common ancestor. We can further subdivide homologous genes into orthologous and paralogous genes.


### I  
[Isoform(s) -](https://elifesciences.org/articles/34477) Proteins that are similar and perform similar roles within the cell.

### J  


### K  


### L  


### M  
[Mate Pair Sequencing -](https://www.illumina.com/science/technology/next-generation-sequencing/mate-pair-sequencing.html#:~:text=Mate%20pair%20sequencing%20involves%20generating,Structural%20variant%20detection) The generation of long-insert paired-end DNA libraries useful for applications like *de novo* sequencing, genome finishing, structural variant detection, and the identification of complex genomic rearrangements.

[Multiple Sequence Alignment (MSA) Programs -](https://www.sciencedirect.com/topics/medicine-and-dentistry/multiple-sequence-alignment#:~:text=A%20multiple%20sequence%20alignment%20(MSA,Bioinformatics%20and%20Computational%20Biology%2C%202019) Software that attempts to align multiple DNA sequences to attain optimal matches.

### N  
[Nucleotide -](https://www.cancer.gov/publications/dictionaries/genetics-dictionary/def/nucleotide) A molecule that makes up DNA and RNA.

### O  
[Orthologous Genes -](https://bio.libretexts.org/Bookshelves/Microbiology/Microbiology_(Boundless)/07%3A_Microbial_Genetics/7.13%3A_Bioinformatics/7.13C%3A_Homologs_Orthologs_and_Paralogs) Homologous genes that diverge after a speciation event, but the gene and its main function are preserved.



### P  
[Paralogous Genes -](https://bio.libretexts.org/Bookshelves/Microbiology/Microbiology_(Boundless)/07%3A_Microbial_Genetics/7.13%3A_Bioinformatics/7.13C%3A_Homologs_Orthologs_and_Paralogs) Genes present in a particular organism that are related to each other through a gene duplication event.



### Q  


### R  
[RNA - ](https://www.genome.gov/genetics-glossary/RNA-Ribonucleic-Acid) Ribonucleic acid (RNA) is a copy of DNA that is used to produce proteins and assists in the translation of DNA.

### S  
[Scaffold -](https://bioinformaticsworkbook.org/introduction/dataTerminology.html#gsc.tab=0) A set of contigs that have been orientated and ordered with either mate-apired or long reads.

[Synathrope - ](https://davidrousefaicp.com/synanthropic-species-why-are-they-important-to-our-future/) Animals that live in close association with humans but are not domesticated.

[Synteny -](https://www.nature.com/scitable/topicpage/synteny-inferring-ancestral-genomes-44022/) The conservation of order of blocks within the order of 2 sets of chromosomes that are being compared to one another.

### T  


### U  


### V  


### W  


### X  


### Y  


### Z  







