---
title: "Progress & Notes: 6/4-6/7"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

## Setting up & using R

I've began setting up and trying to work in R through creating the R markdown and workflowR packages.
I discovered that it is **necessary to have pandoc downloaded** in order to edit these files in VS Code, and add these 
files into the environment variable paths.  

## Beginning Work on Orthoptera Genomes

I began work on the table and have now recorded the necessary information for 24 species across 7 orders. This table has been published to the R markdown site and a second table has recorded the requested statistics for each order (number of assemblies, number of annotated assemblies, etc.).

I have decided to spend the rest of today (Friday) reading the papers Maeva has given us on TOGA and gene content evolution in arthropods.

## Goals for next week
- Get workflowR site set up totally (theme, menus, etc.)
- Have tables finished & begin processing genomes
- Finish reading *Gene content evolution in the arthropods*  
