---
title: "Progress & Notes: 7/29-8/2"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
    toc_float: true
    toc_collapsed: false
    theme: default
    css: "theme3.css"
toc_depth: 1
number_sections: true
editor_options:
  chunk_output_type: console
---

## Updates {.tabset}

### make_lastz_chains
*Monday:*  
Last week I got responses from Dr. Hiller and Michael in IT, as well as met with Devon on Wednesday. Their recommendations were as follows:

  1. Try running make_lastz_chains in a conda environment
  2. Run repeat modeler and masker on the genomes we're trying to chain with
  3. Change cluster specifications to try and run on Grace
  
I am already running repeat modeler on the Idaho Mormon cricket today and I will also have *S. Gregaria* and the Colorado Mormon cricket done by the end of the week as well.


### Repeat Modeler & Masker
*Monday:*  
I am currently (Monday) running repeat modeler on the Idaho Mormon cricket and will run masker on it after it is finished but so far I have only had syntax errors.

### Braker
*Monday:*  
When I did the mapping of the sub-sequences of the *S. Gregaria* SRA data to the genome it didn't create the .sam file with SQ headers, so I am having to rerun this step with additional flags to get these headers to then turn the file into a BAM format and then run it into Braker.

*Tuesday:*  
(4:17 pm) Mapping was successful, data is now in a BAM file format and I am waiting for memory on the on-demand cluster to load the singularity image.

*Wednesday:* I am still waiting on my remote environment to be activated on the Grace OnDemand portal so that I can use Singularity. It has been pending for nearly 24 hours :(
