---
title: "Progress & Notes: 7/15-7/19"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
    toc_float: true
    toc_collapsed: false
    theme: default
    css: "theme3.css"
toc_depth: 1
number_sections: true
editor_options:
  chunk_output_type: console
---

**Monday:** Today Jackson and I met with Devon and he consulted on both the best implementation of BRAKER and the errors the make_lastz_chains is throwing. 

  BRAKER3: He said he believed that the best way to run BRAKER is in a singularity channel and to run 2 different models for the mormon cricket genomes. This will give what he calls the "structural" annotation and then he suggested that we intersect the .gtf files and remove the common genomes and run InterPro on the non-common genomes. 
  
  make_lastz_chains: Since Michael added the missing dependency, the py_nf (Nextflow) module can't be found. He said I could get it running in an Anaconda environment on my own or I could wait for Michael to respond. I will give Michael a bit to try and correct it, as I tried previously and again after the meeting to get it running in a conda environment on Grace but I haven't been able to configure everything correctly yet.

**Wednesday:** 

  BRAKER3: I emailed Dr. Hoff yesterday to consult on the best workflow to implement for BRAKER3 using our data, and she said that following the steps for IsoSeq Reads in Singularity on [this poster](https://github.com/Gaius-Augustus/BRAKER/blob/master/docs/posters/poster_PAG2024.pdf) on the BRAKER3 GitHub.
  
  make_lastz_chains: Michael added the py_nf module to the make_lastz_chains/1.0.0 module on Grace but now it is throwing an error when trying to run Nextflow. I have emailed him the error and am waiting for a response. I also have a meeting scheduled with Devon for Friday at 1 so is Michael can't help he may be able to.
  
**Friday:**

  BRAKER3: I am still trying to prepare files for my initial BRAKER3 run, I'm currently on the mapping stage. After it finishes I'm going to try a run with it unsorted in BRAKER and then another run that is sorted to see if it affects the pipeline at all. 
  
  make_lastz_chains: Emailed Michael on Wednesday but still no answer. Not expecting much by EOD because of the Microsoft outage affecting university operations.
  
  Plan for next week: I plan on running repeat modeler and repeat masker on Monday, as well as completing my initial BRAKER runs. I will continue correspondence with Michael about make_lastz_chains, as well as wait for responses from Dr. Kirilenko, Dr. Hiller, and Dr. Oh on how to troubleshoot. I am not sure if I'll be able to begin the Mormon Cricket alignments or not since I have an exam on Friday, but I will try to make enough progress to where I can begin it next Monday.
