---
title: "Progress & Notes: 8/19 - 8/30"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
    toc_float: true
    toc_collapsed: false
    theme: default
    css: "theme3.css"
toc_depth: 1
number_sections: true
editor_options:
  chunk_output_type: console
---

I have began rerunning repeat masker after receiving my SU increase from Dr. Song. I have contacted Julia about sending me the pipeline information to run on the Mormon cricket species, but she has not sent me the information yet. This task has been delayed because we have both been off at separate times this month. I am trying to schedule a meeting with Maeva for next week, possibly Monday at 9 pm CDT / 10 am JST. 

I am also in the process of figuring out my class schedule, so I haven't been able to go into lab in person this week at all. Additionally, my travel plans were delayed and I didn't back until Tuesday so my week was shortened to begin with (ugh). All this to say, I will set a hard schedule for myself over the weekend now that I understand my classes a bit better and make sure I'm in person next week. 

**8/26:** I've set up a conda environment with the newest version of make_lastz_chains, nextflow, and lastz and will continue to troubleshoot as the program will not run yet. Also, the Colorado and Idaho Mormon cricket genomes have been masked and modeled, I'm just waiting on Gregaria to finish.
